site_domain: pulpprogramming.com
build_type: production
markdown: rdiscount
pygments: true

expires:
  html: 3600 # one hour
  assets: 1314000 # one year


# basic configuration
source: ./source
destination: ./_site
permalink: /blog/:year/:month/:day/:title.html
# permalink: /posts/:title.html

paginate: 2
# header
title: Pulp Programming
subtitle: less of a cathedral, more of a bazaar

style: pulp

# your disqus id or False if you don't want comments
disqus: False
