
markdown: rdiscount
pygments: true
site_domain: pulpprogramming.com
build_type: production

expires:
  html: 3600 # one hour
  assets: 1314000 # one year

exclude: theme-resources.txt #, Rakefile


# basic configuration

destination: ./_site
plugins: ./source/_plugins
permalink: /posts/:title.html

paginate: 2
# header
title: Pulp Programming
subtitle: less of a cathedral, more of a bazaar

style: pulp

# your disqus id or False if you don't want comments
disqus: False

# the following are required for RSS to work
# remember not to end the 'root' with a slash:
root: http://pulpprogramming.com
author: dnc
email: dcvetinovic@gmail.com

redirects:
